### ISSUE TITLE
Robot Logo

### ISSUE THREAD

**Issue by matthewp** [matthewp/robot#103]
Hey everyone, I'm thinking about giving Robot a logo that's not just the robot emoji.

I created this, derived from an open license artwork I found online:

![possible Robot logo](https://user-images.githubusercontent.com/361671/77121115-d8f24b00-6a10-11ea-997e-0dede9382edc.png)

I like it, but if other more artistic people want to jump in that would be great too.  Or just give your opinions.

Personally I like the idea of a robot head. A full robot would be nice too, but for stickers the head seems like the right dimensions to me. Would love to hear what you think.

**Comment by craftedsystems** [comment]
This robot looks small and functional, too. :-)

![Robot](https://user-images.githubusercontent.com/26137287/78894882-30af2f80-7a6e-11ea-9845-e6af285e5b47.jpg)

**Comment by matthewp** [comment]
@craftedsystems That's pretty nice, did you create it?

**Comment by craftedsystems** [comment]
@matthewp yes, I did a quick draft in Illustrator. If you like it, I will upload it as a vector file. Further refinement is fine too.

**Comment by matthewp** [comment]
Great! What I really like about it is simplicity and not too much color, and i like the antennas with electricity going between thing. What I'm not sure about is, is it too "human"? Maybe it's the roundness of it that makes me feel that way. I think Robot should be more of an assistant robot (since it makes your programs function) and less of a friend, if that makes sense. So I wonder if more of a square look and probably without a smile would help. What do you think?

**Comment by craftedsystems** [comment]
How about something like that?  
(sketch)
![Robot-2](https://user-images.githubusercontent.com/26137287/79048342-b7a20a80-7c1c-11ea-9883-9efd59ab2dbe.png)

**Comment by craftedsystems** [comment]
@matthewp you mentioned stickers :-)

![Robot-3-Stickers](https://user-images.githubusercontent.com/26137287/79049772-d789fc00-7c25-11ea-809d-b38a620fddc3.jpg)

**Comment by matthewp** [comment]
I love it! Do you think the background should always be part of the logo, or would that sometimes be used (for example with stickers) and sometimes not (maybe on the website). If it should always be used, do you think it matches the theme of the website? https://thisrobot.life/. The theme of the website is based on is roughly this: https://www.schemecolor.com/metal-robot-color-scheme.php

I really appreciate this!

**Comment by craftedsystems** [comment]
I'm glad you love it. 🎉 😄  
I think the robot would need a kind of body if used without a background. Currently, I can not imagine this head without a context, like a circle or any background/box.
Adjusting the color is very flexible. I used the linked color theme and pasted the robot into the screenshot. What do you think?

![Robot-3 1](https://user-images.githubusercontent.com/26137287/79116147-fd2f1680-7d87-11ea-9c73-ba608ddf2d07.png)

![website](https://user-images.githubusercontent.com/26137287/79116153-015b3400-7d88-11ea-8840-1c88b37e43a5.png)

**Comment by craftedsystems** [comment]
another (minimal) variant

![Robot-3 3](https://user-images.githubusercontent.com/26137287/79122704-b1d13400-7d98-11ea-9aa2-6122d2d08db8.png)

**Comment by craftedsystems** [comment]
@matthewp, I came here to try your library and ended up drawing a robot. My favorite type of distraction.

**Comment by matthewp** [comment]
Hah! I appreciate it 😀. I actually love all 3 variants. Maybe we can just keep them all?  I do like the grey version for the website quite a lot. Would look fantastic as a sticker as well....

I think at this point I should set up a GitHub repo for the logo and give you write access.

**Comment by matthewp** [comment]
Hey @craftedsystems, I've created https://github.com/matthewp/robot-logo and gave you an invite. I think we can go with the same license as this project (BSD-2-Clause) which is what other projects seem to do, if that's fine with you.

**Comment by craftedsystems** [comment]
Hi @matthewp, I pushed the logo graphics data from this thread.
https://github.com/matthewp/robot-logo/commit/f41f7e2d16b3064a292190d49e1cf7d5a09b07fe
Let's move the discussion over to the new robot-logo repository.

**Comment by matthewp** [comment]
Thank you @craftedsystems! I have a pretty busy week so I likely won't be able to advance this very far until possibly this weekend. In the meantime I opened an issue about the license: https://github.com/matthewp/robot-logo/issues/1

I'll leave this issue open until a version is added to the website. Thanks again, you rock!

**Comment by matthewp** [comment]
This is out! https://thisrobot.life/ Thanks so much @craftedsystems for creating this. Credit is given to you in the footer on each page.

**Comment by kayodebristol** [comment]
Matthew,
The page is out of proportion on mobile browser (only place I've checked).
Huge logo, normal size everything else. But, other than that, love the new
logo.

Maybe something is cached or hasn't updated on my end.

**Comment by matthewp** [comment]
It's probably CloudFront's overly aggressive caching of the styles, it gets cleared in a day. But I'll check it out myself to confirm there's not a problem. Thanks @kayodebristol  !

**Comment by kayodebristol** [comment]
@matthewp - the caching issue appears to be resolved.

**Comment by matthewp** [comment]
Thanks!
