### ISSUE TITLE
\node_modules\lit-robot\machine.js:1:26: Cannot resolve dependency 'robot3'

### ISSUE THREAD

**Issue by chisholmd** [matthewp/robot#110]
Do I need to install robot...before lit-robot?  Or is something going on?

**Comment by matthewp** [comment]
I think they do both need to be installed, yes.

**Comment by ehuelsmann** [comment]
@chisholmd is this still an issue?

**Comment by matthewp** [comment]
This is old enough that I think it's safe to close :)
