### ISSUE TITLE
Service missing child field in Typescript definitions

### ISSUE THREAD

**Issue by Ghirigoro** [matthewp/robot#128]
Service has a dynamic field `child` that is not accessible through the Typescript definitions. 

I can see why it's hard to type this since the field is dynamically added and deleted from the service object. Any reason why it's not a permanent field of service that is nulled out rather than deleted as necessary?

P.S. - for anyone else running into this issue, you can access `child` by indexing the service object: `service['child']`

**Comment by acd02** [comment]
👋  @matthewp, first off, thanks for the lib 💪 

I just opened a PR (#173 ) addressing this issue, if you don't mind taking a look when you have some time 👍

**Comment by acd02** [comment]
hey @Ghirigoro,

Since #173 was merged and addressed this issue, we can close this, imho.

**Comment by matthewp** [comment]
Yep, thanks!
