### ISSUE TITLE
`invoke` typescript definition issue

### ISSUE THREAD

**Issue by jackmellis** [matthewp/robot#142]
I just upgraded from 0.2.18 to 0.2.19 and got hit by a tonne of typescript issues for `invoke`.

It looks like the args have been tightened up from `...any[]` to `fn: (ctx) => Promise`

https://github.com/matthewp/robot/compare/v0.2.18...v0.2.19#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R102

But from my usage (unless this has changed) the function passed to invoke also takes an event argument?

**Comment by matthewp** [comment]
Mind sending a pR?

**Comment by frederikhors** [comment]
Same here. A lot of confusion. How to fix this?

**Comment by frederikhors** [comment]
This is the commit. But here I see two invoke definitions... https://github.com/matthewp/robot/commit/aa34adfa636d96c4869067bfd3bd37c4606eaf03#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8

**Comment by ehuelsmann** [comment]
> This is the commit. But here I see two invoke definitions... [aa34adf#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8](https://github.com/matthewp/robot/commit/aa34adfa636d96c4869067bfd3bd37c4606eaf03#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8)

@frederikhors, @jackmellis : there are two `invoke` definitions: one is the "machine" type invocation. The other (the one you're reporting your issue with) is the "function" type invocation. I think you're right that the typescript definition is too tight. A PR would still be nice.

**Comment by ehuelsmann** [comment]
@matthewp agreed this needs adjustment of the `invoke()` typescript definition?

**Comment by matthewp** [comment]
Sure, I can take a look

**Comment by matthewp** [comment]
This was already fixed in https://github.com/matthewp/robot/pull/174. Please file a new issue if there's still a problem.
