### ISSUE TITLE
[Question]: Update context from outside of machine.

### ISSUE THREAD

**Issue by Tkach7** [matthewp/robot#145]
Hi there!
So, first of all, thank you for the great stuff. Robot is so nice tool and i enjoy using it in the my project :) 
My question is about updating context once machine has already been created. Lets imagine case with react component where we use `useMachine`, also this component expects async data from the props. Is it possible to update existing machine context or better to render component with machine only when we get all expected data?
```
const componentWithMachine = ({ asyncData } => {
const [current, send] = useMachine(machine, initialContext);

useEffect(() => {
// actions for updating machine
}, [asyncData])

render ...
});
```

I was thinking about some provider with  `interpret` which returns new service. However i am not sure how to create new [current, send]...

```
const INITIAL_CONTEXT = {
  fieldFromContext: 'foo',
}
const context = (context = INITIAL_CONTEXT, event) => {
    return {...context, ...event};
}
const initialMachine = createMachine({...}, context);

export function useMachineProvider({ fieldFromContext }) {
    const [service, setService] = useState(interpret(initialMachine));
    const [current, send] = useMachine(service.machine, service.context);

    useEffect(() => {
        if (current.context.fieldFromContext !== fieldFromContext) {
            const newService = interpret(service.machine, undefined,  undefined, {
                ...current.context,
                fieldFromContext,
            }));
            setService(newService);
        }
    }, [fieldFromContext, current.context.fieldFromContext, service.machine]);

    return [current, send];
}
```

Example of usage:
```
function Component({asyncData}) {
   const [current, send] = useMachineProvider({ fieldFromContext:  asyncData });
}
```

**Comment by HipsterBrown** [comment]
I think this depends on how you design your machine. If you have some kind of `pending` state as the initial, then transition to a `ready` state once the `asyncData` is available, your first example with the `useEffect` call would work just fine.

```ts
const machine = createMachine({
  pending: state(
    transition('ready', 'received_data',
      reduce((ctx, ev) => ({ ...ctx, data: ev.data }))
    )
  ),
  ready: state(/* other transitions here */),
})
```

Otherwise, the async data could be reqested / fetched in an invoked service, so you don't need to react to it in a `useEffect`:

```ts
const machine = createMachine({
  pending: invoke(getAsyncData,
    transition('done', 'ready',
      reduce((ctx, ev) => ({ ...ctx, data: ev.data }))
    ),
    transition('error', 'invalid')
  ),
  ready: state(/* other transitions here */),
});
```

**Comment by matthewp** [comment]
Agree with @HipsterBrown here, better to put loading type of logic into the machine itself. Of course `service.context` is a mutable object so there's nothing stopping you from doing that, I just wouldn't recommend it. FSMs are made for this sort of thing, use them! 😀

**Comment by Tkach7** [comment]
Ah, great! Honestly, i didnt think about pending state, its definitely better than context mutation from out of scope 👍  Thanks guys.
