### ISSUE TITLE
How to pass an initial state to a child machine, without using the parent-context?

### ISSUE THREAD

**Issue by wuarmin** [matthewp/robot#150]
Hello,

Maybe somebody can help me. My issue is described via code comments.

I have following machine: 

```js
createMachine(
  {
    search: state(
      transition(
        "search",
        "validateSearch",
        reduce((context, { searchParams }) => {
          return {
            ...context,
            searchParams,
          };
        })
      )
    ),
    validateSearch: state(
      immediate(
        "invokeSearch",
        guard(
          ({ searchParams }) => {
            return validSearch();
          }
        )
      ),
      immediate(
        "invalidSearch" // here would be the right place to compute the correct error message, but I don't know how to put it into the child machine, without using the parent context
      )
    ),
    invalidSearch: invoke(
      createMachine({ // modalMachine /  how is it possible to put the correct error message from validateSearch state to modalMachine?
        show: state(transition("hideModal", "hide")),
        hide: state(),
      })
    ),
  },
  (initialContext) => ({ ...initialContext })
);
```

Best regards

**Comment by matthewp** [comment]
When you invoke your machine you are passed the parent service's context. So add a second argument to the inner `createMachine` receiving the parent context and doing whatever you need with it.

**Comment by wuarmin** [comment]
@matthewp after intensive work with your great lib, the above issue passed away for me 😉

But I have a further question:
It would be great to know the parent machine state(s), while a child machine is running.
I.e. parent state is: `submitError` and child state is `showModal` - > `current.name` is `showModal`. I have the need to know also the parent state (i.e. `submitError-showModal`). 

That's because I reuse the modalMachine and so I have to know, which modal has to be shown (the submitError modal, or the success Modal). 
Thx

**Comment by matthewp** [comment]
Can you not pass that information in at the time of creating the modal machine?

**Comment by wuarmin** [comment]
Yes that's possible, for sure. I solved it this way, but I thought, if I could read out the parent state, then I wouldn't have to manage another prop holding a state-like attr.

**Comment by matthewp** [comment]
Under the hood invoking a machine is just like calling `interpret(machine, ...)`, so there's no connection to the parent service unless that connection is passed through.
