### ISSUE TITLE
API: Consider renaming `interpret()` to `createService()`

### ISSUE THREAD

**Issue by Zearin** [matthewp/robot#165]
The `interpret()` function returns something called a _service_ everywhere else in the docs.  

When I was first trying to learn Robot to use in a project of mine, it took me a couple of re-reads for this to sink in.  That’s because the other functions return things that match the function name: `createMachine()` returns a _machine_, `transition()` returns a _transition_, `state()` returns a _state_, and so on.

(I don’t normally feel comfortable requesting a change to an API name.  However, since Robot is still at version 0.2.x, I suppose this is the appropriate time (before v1.x) to do so.)

Consider renaming `interpret()` to `createService()`. This would make the function match what we call the thing it returns.

It would also make the only 2 top-level functions in Robot start with “create…”.  That would be a nice cue that both functions are at that level.

**Comment by matthewp** [comment]
Personally I'd rather get rid of services altogether. I just haven't figured out how yet :)

**Comment by Zearin** [comment]
Until you figure out how, can I do this rename in a Pull Request? :)  (Including updating the docs!)

**Comment by Zearin** [comment]
@matthewp ping :)

**Comment by Zearin** [comment]
@matthewp **QQ:** Can you elaborate on your wish to drop services completely?

(i.e., are you talking about something like `const fsm = createMachine({…}); fsm.run()`?)

**Comment by ehuelsmann** [comment]
@Zearin see #106 for the line along @matthewp 's thinking.

**Comment by matthewp** [comment]
Yeah, thanks for calling that out @ehuelsmann. I don't think a rename accomplishes anything, so I'm going to close.

**Comment by Zearin** [comment]
I was proposing a simple name-change (and docs update) to make robot easier to learn. 

You are discussing (what sounds like) a major rewrite of a big part of the project. 

I don't see why one had to block the other. But it's been years since I opened this. 

Glad to see some activity picking up on the project again, though. 

Whatever the rewrite turns out to be, I hope to check it out as soon as it lands! 👍

**Comment by matthewp** [comment]
I understand what you mean. But changing a name is a breaking change. If we haven't figured out services by the time 2.0 is released maybe we can consider it.
