### ISSUE TITLE
Deadly traffic light

### ISSUE THREAD

**Issue by hypeJunction** [matthewp/robot#167]
https://github.com/matthewp/robot/blob/4f242ae4976215c58cdc367db1a7fc2bc63263d3/demos/stoplight.js#L3

So I was looking at that example and was lost for a minute. A traffic light goes from green to yellow to red to yellow to green. In your example it just loops.

**Comment by matthewp** [comment]
Is this a cultural thing? In the U.S. traffic lights do not go from red to yellow to green.

**Comment by hypeJunction** [comment]
Woah. I have learnt something new today. From a pedestrian perspective seems quite dangerous that there is no warning that cars are about to run over you, but then again US has no pedestrians, so I suppose it's cultural. https://m.youtube.com/watch?v=bznLyIHX7nA

**Comment by matthewp** [comment]
We have a separate pedestrian light that usually counts down from 10 when it is about to turn red. There's even an example of such a crosswalk here: https://thisrobot.life/guides/nested-states.html (though without the countdown)
