### ISSUE TITLE
A library to visualise Robot3 state machines

### ISSUE THREAD

**Issue by jbreckmckye** [matthewp/robot#178]
I already shared this on Twitter, but I thought I would raise an 'issue' to give it more visibility.

[Robot3-Viz](https://github.com/jbreckmckye/robot3-viz) is a library for visualising Robot 3 finite state machines. You can use it with a plain JS API or with React.

For instance, given a state machine like

```typescript
export const invokePromises = createMachine({
  idle: state(
    transition('load', 'loading')
  ),
  loading: invoke(async () => Promise.resolve(true),
    transition('done', 'idle',
      reduce((ctx: any, ev: any) => ({ ...ctx, user: ev.data }))
    ),
    transition('error', 'error',
      reduce((ctx: any, ev: any) => ({ ...ctx, error: ev.error }))
    ),
    transition('abort', 'idle')
  ),
  error: state()
})
````

The library outputs a visualisation like this

![image](https://raw.githubusercontent.com/jbreckmckye/robot3-viz/master/test/example/pngs/promises.png)

The library requires a DOM to render. If you want to use it as part of an automated process, it needs to be on a machine with either a screenbuffer or XVFB.

Documentation and more examples are in the [README](https://github.com/jbreckmckye/robot3-viz).

**Comment by matthewp** [comment]
Whoa! Did you tag me? I must have missed it.
