### ISSUE TITLE
[bug?] Nested machines immediate issue

### ISSUE THREAD

**Issue by kybarg** [matthewp/robot#195]
When using `invoke` to run nested machines `current` doenst't represent deepest child

Here is example
https://codesandbox.io/s/react-robot-bug-example-re781

https://github.com/matthewp/robot/blob/31d81256f49f9a04b864c25598b63459c6dffda6/machine.js#L174-L181
this quick fix helped, but this looks wrong😁
```diff
let service = {
  send(event) {
    this.machine = send(this, event);

    // TODO detect change
-    this.onChange(this);
+    this.onChange(this.child || this)
  }
};
```

**Comment by afn** [comment]
This appears to remain an issue in the latest version (0.4.0).
