### ISSUE TITLE
Feature request: Official qwik integration

### ISSUE THREAD

**Issue by kee-oth** [matthewp/robot#197]
qwik is a fundamentally different framework for creating server-side-first web applications. It features resumability instead of hydration for making content interactive in the browser. It results in more performant and lighter-weight web applications.

It creates some problems with regards to integrating with certain libraries however. Two other state machine libraries are unable to make a clean integration. There's no way to easily serialize XState machines. And Zag.js usage is blocked because of the way it needs to handle `event.preventDefault()`.

I'm wondering if Robot would consider trying to create an official qwik integration. There's a lot of people wanting a state machine library for usage within qwik applications and Robot could take advantage of this and become the standard for this use case. 

Relevant links:

qwik
https://qwik.builder.io

qwik GitHub issue: State machine as first class concept
https://github.com/BuilderIO/qwik/issues/1171

Zag.js GitHub issue: qwik integration
https://github.com/chakra-ui/zag/discussions/392

Thanks!

**Comment by ehuelsmann** [comment]
@kee-oth, how did you solve the problem that this integration currently does not exist? Did you write your own?

I'd like to invite the people who want a state machine in qwik to submit (and maintain) an integration. I'll discuss with @matthewp, but I believe we'll be happy to host and release it.

**Comment by matthewp** [comment]
Actually I don't think I'd want a qwik integration. Maintaining these integrations are a non-trivial amount of work, so I'd like to stick to those where we have active maintainers who are using said integration. I think I'm likely to remove some of the ones we already have, the Haunted one for example, at a later time.

**Comment by ehuelsmann** [comment]
In that case, lets close this issue. There was indeed a reason I added the "(and maintain)" bit in my comment above.

**Comment by matthewp** [comment]
@ehuelsmann Yeah totally, I just think they should come from existing contributors. Someone might PR an integration but we don't know if they are going to maintain it. If it turns out they do not, it becomes a burden on us to do. But if someone is an existing contributor we have more confidence that they'll continue to maintain it. That's my reasoning anyway.

**Comment by brandonpittman** [comment]
I was hoping to see this one happen. 😢

**Comment by brandonpittman** [comment]
I was hoping to see this one happen. 😢

**Comment by matthewp** [comment]
I encourage anyone interested in this to create their own integration. If it becomes popular enough we can consider bringing it into core, if the maintainer desires.
