### ISSUE TITLE
How to start and await for a state machine's asynchronous execution?

### ISSUE THREAD

**Issue by mpenna** [matthewp/robot#206]
I have this scenario where the state machine will be frequently triggered/started by an external process (e.g.: a cron-like task manager), which will need to block until whatever asynchronous processing the state machine has been configured to execute finishes. Is this achievable? State would be serialized/persisted and pulled/hydrated back upon every triggered execution. However, I'm not sure how the blocking of the external (controller) process would be handled.

Thanks.

**Comment by matthewp** [comment]
Your finish is "finished" when it hits a final state, a state which has no transitions. What I would probably do is something like this:

```js
let resolve;
let promise = new Promise(_resolve => {
  resolve = _resolve;
})

service = interpret(machine, () => {
  if(machine.state.value.final) {
    resolve();
  }
});

await promise;
// All done!
```

**Comment by mpenna** [comment]
Nice! Let me try that strategy out and see how it goes. 

Thanks!

**Comment by mpenna** [comment]
It's been a long time since I last looked and touched this project, but if my memory serves me well, yes, I believe it did work. 

Thanks and sorry for replying sooner.

**Comment by ehuelsmann** [comment]
@matthewp I propose to close this issue based on the response above.

**Comment by ehuelsmann** [comment]
@matthewp , I think it'd make sense add a guide or section with "recommended patterns".

**Comment by matthewp** [comment]
@ehuelsmann yeah we can close this. And yeah, we have that with our guides: https://thisrobot.life/guides.html which explains a couple of patterns like this. So could add some docs there.

**Comment by ehuelsmann** [comment]
I'll issue a PR adding a micro-guide. Then we'll be able to close this issue with that PR.
