### ISSUE TITLE
[bug] Invoke should fire transitions only within its state

### ISSUE THREAD

**Issue by kybarg** [matthewp/robot#213]
If invoke promise and skip it before it is resovled, it will fire `done` or `error` on current state
I think it should do nothing if state has chnaged.

https://codesandbox.io/p/sandbox/cocky-engelbart-gxs57j

Just remembered that this is duplicate of #141 #171  #208

**Comment by ehuelsmann** [comment]
Isn't this addressed by https://github.com/matthewp/robot/commit/1fc7737ce0305b7b3b775303d77d3589e1b5ad8c which is part of the released robot versions v1.0.0 and v1.0.1?

**Comment by ehuelsmann** [comment]
Yep. This bug is fixed and released in `v1.0.0` and `v1.0.1`.
