### ISSUE TITLE
test failures on GitHub Actions (Browser environment crashing)

### ISSUE THREAD

**Issue by ehuelsmann** [matthewp/robot#227]
@matthewp After merging, I discovered the test failed due to the browser crashing. I'll have a look at what could be going on tomorrow.

**Comment by matthewp** [comment]
@ehuelsmann looking at the logs it appears to be a segfault, which the browser shouldn't be doing. This feels like more likely a random thing. I bet restarting the test would cause it to succeed.

I'm not overly worried about this unless it becomes a repeated failure.

**Comment by matthewp** [comment]
It is happening consistently. I'll take a look. An outdated dependency is likely the reason.
