### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by TehShrike** [matthewp/robot#41]
I was feeling too guilty to open a "TypeScript herp derp?" issue when I found this project, but then I found [this tweet](https://twitter.com/matthewcp/status/1175456131285757959), so here we are.

There are two main ways to add types – convert the source to TypeScript, and generate the JS and type file from that, or leave the source as the current JS, and add an index.d.ts with separate tests for the types.

Do you feel a preference for one or the other for this project?

**Comment by matthewp** [comment]
I think I'd like to keep the project in JS as long as I can 😀.  Since the project is so small I don't think it will be as much of an issue to maintain a definition file. So yeah, I'll start on this soon. Thanks for the issue!

**Comment by Glazy** [comment]
Hey @matthewp!

First of all, great library - looking forward to playing around with it some more. Have you made any progress on these types? :pray:

**Comment by matthewp** [comment]
I haven't yet, no. Will be through a index.d.ts file. Happy to take contributions.

**Comment by matthewp** [comment]
This was added in #63 and is available in robot3 0.2.8
