### ISSUE TITLE
Add element instance to context for lit-robot.

### ISSUE THREAD

**Issue by robdodson** [matthewp/robot#43]
Example: https://codesandbox.io/s/robot-playground-xzfr0

For LitElement, it may be useful to provide easy access to the element instance so folks can do things like set properties during `invoke()`.

**Comment by matthewp** [comment]
Thinking more about it I think the thing to do here is to make it possible to receive data as part of the context function like so:

```js
const context = ({ element }) => ({
   element,
   other: 'stuff'
});

const machine = createMachine({
  idle: state()
}, context);

interpret(machine, onChange, { element: el });
```

Then change lit-robot so it passes in the element like above.

**Comment by matthewp** [comment]
First part of this change in in #44 

Followup will occur in https://github.com/matthewp/lit-robot/issues/2
