### ISSUE TITLE
Create a Svelte integration

### ISSUE THREAD

**Issue by matthewp** [matthewp/robot#47]
Based on this: https://twitter.com/Rich_Harris/status/1175415662757535746

**Comment by JustinVoitel** [comment]
Would love to see a official svelte integration! 
I tried to create a basic example with the machine context:
https://svelte.dev/repl/9d07c1e4247243358a5177d6640acf81?version=3.12.1
but iam not sure if thats the optimal approach, maybe return a object from useMachine if we wanna be able to get more info out of the machine

**Comment by SirNavith** [comment]
I wrote a similar API to @JustinVoitel
https://svelte.dev/repl/147b9026049f4fa1813bfbd3f678a4aa?version=3.12.1

**Comment by kayodebristol** [comment]
This approach uses service as a svelte store.
https://svelte.dev/repl/a9904c210b474bd2ab71d9b7c26c4c38?version=3.12.1
Hopefully someone can provide feedback, so I can look for a better approach if this one has issues.
It's simple, which to me is the biggest selling point.

**Comment by matthewp** [comment]
That looks pretty brilliant! If you have docs I'd be happy to link to those alongside the other integrations.

**Comment by kayodebristol** [comment]
Thanks. I'll write it up and stage it in a few days; with better examples.

**Comment by kayodebristol** [comment]
Added a basic [write up](https://github.com/kayodebristol/svelte-robot-factory). 
Will push more examples over time.

**Comment by matthewp** [comment]
Great! Going to leave this issue open so I remember to add a link.

**Comment by kayodebristol** [comment]
Happy to do a pull request if you want to create a repo for this, so it conforms with the other integrations.

**Comment by matthewp** [comment]
Hey @kayodebristol, sorry for taking so long to respond. If you're still interested it would be great to have the integration here: https://github.com/matthewp/robot/tree/master/docs/integrations. If you wouldn't mind submitting a PR there that adds docs and links to your GitHub repo that would be great. 🙏

**Comment by kayodebristol** [comment]
@matthewp Thanks for everything. I think this issue/enhancement can be closed.
