### ISSUE TITLE
Possibility to extend a machines invoke functions?

### ISSUE THREAD

**Issue by Avocher** [matthewp/robot#53]
Is there a way to extend machines like in xstate: https://xstate.js.org/docs/guides/machines.html#extending-machines. I would specifically be interested in overriding my invoked functions so i can reuse my machines. 

My example use case is a form machines fetching data from different apis that have very different reponse formats.

**Comment by matthewp** [comment]
With Robot reuse comes through composition. So I would suggest defining something like:

```js
function formsMachine(fetch) {
  return createMachine({
    one: invoke(fetch) // ...
  })
}

const usersPageMachine = formsMachine(() => fetch('/api/foo'));
const adminPageMachine = formsMachine(() => fetch('/api/bar'));
```
