### ISSUE TITLE
Compile code for old browsers support

### ISSUE THREAD

**Issue by batusai513** [matthewp/robot#70]
Hi, I've been using this module for a little while but just figured out that the app we are working on is not working on old browsers because the es2015+ syntax is not being compiled down to support those browsers, It would be possible to configure the build to generate es5 compatible code?, I can make a PR for that (this is also happening on the integrations libraries).

Thanks.

**Comment by matthewp** [comment]
Can't you compile it to ES5 in your app?

**Comment by batusai513** [comment]
Right now it's not a viable option here, We are excluding the `node_modules` folder from the babel compile :(

**Comment by matthewp** [comment]
Can't you change your config so that it doesn't exclude node_modules from babel? Or exclude it from everything other than Robot?

Another thing I've done some times is babel compile the bundles rather than compile individual modules during bundling.

**Comment by batusai513** [comment]
Yes, I've just included robot3, react-robot and robot-hooks to be compiled by babel and it worked.

Thanks :)
