### ISSUE TITLE
How to use the unpkg version of this?

### ISSUE THREAD

**Issue by pke** [matthewp/robot#81]
I can't seem to get the exports from the published module at
`import { createMachine } from "https://unpkg.com/robot3@0.2.9/dist/machine.js"`

It errors with:
```bash
Uncaught SyntaxError: The requested module 'https://unpkg.com/robot3@0.2.9/dist/machine.js?module' does not provide an export named 'createMachine'
``` 

Maybe the module should export using `module.exports` instead of just `exports`?

I got it working using:
`import { createMachine, state, transition } from "https://unpkg.com/robot3@0.2.9/machine.js"`

However `preact-robot` is not properly hosted on unpkg (it tries to import from `preact-hooks`). So is there a way to get robot running with webmodules instead of transpiling?

**Comment by matthewp** [comment]
Are we missing the module field in package.json maybe?

**Comment by pke** [comment]
No clue ;) Never published to unpkg. I don't even know how it works. Do they pull the packages from npm?

**Comment by matthewp** [comment]
If you use `https://unpkg.com/preact-robot?module` and `https://unpkg.com/robot3@0.2.9/machine.js?module` it looks like it should do the right thing.

**Comment by matthewp** [comment]
Closing as I think this is correct.
