### ISSUE TITLE
Import broken in Node.js

### ISSUE THREAD

**Issue by rektide** [matthewp/robot#84]
Hey there hello!

Package.json specifies [`"type": "module"`](https://github.com/matthewp/robot/blob/master/package.json#L7) so Node,js (>=13.5.0, which have esm support) tries to load robot3 as a module.

But in the build dist/machine.js file, the first line is `Object.defineProperty(exports, '__esModule', { value: true });`.

This breaks Node.js, which issues: `Uncaught ReferenceError: exports is not defined`.

## Workaround

`import("robot3/machine.js")` works, as this file is esm.

**Comment by matthewp** [comment]
Hm, so changing the main to the module would fix Node >13.5, but break older versions. I'm not sure what to do here...

**Comment by matthewp** [comment]
I think changing the dist/machine.js to dist/machine.cjs will fix it.
